---
{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-dynamic
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
data:
  zookeeper.dynamic:
    {{range $i := until (.Values.clustersize|int)}}
      server.{{$i|add1}}={{$root.Chart.Name}}-{{$i}}.zookeeper-headless.default.svc.cluster.local:2888:3888;2181
    {{end}}
