---
{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
data:
  zookeeper.properties: |
    tickTime=2000
    dataDir=/opt/zookeeper/data
    maxClientCnxns=3000
    initLimit=100
    syncLimit=100
    4lw.commands.whitelist=ruok, imok, mntr
    standaloneEnabled=false
    dynamicConfigFile=/opt/zookeeper/dynamic/zookeeper.dynamic
