---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
  - port: 2888
    name: zkp-server
  - port: 3888
    name: zkp-leader
  selector:
    app: {{ .Chart.Name }}
